<div class="game-info">
    <!-- logo尺寸为默认120*120 -->
    <a href="../index.html" class="nav-logo"><img src="images/logo.png" alt="" width="117" height="117"></a>
    <h2>星际火线</h2>
    <p>星际\射击\动作</p>
    <a href="javascript:;" class="game-desc-swit">
        <span>游戏介绍</span>
        <div class="game-desc">
            《星际火线》是一款3D动作射击手游。次时代3D，呈现震撼未来战场；三枪一体，成就无敌枪械大师；独创飞翼，带你穿越星际；现已开启革新测试，超多游戏内容不容错过
        </div>
    </a>
</div>
<ul class="fl nav-list">
    <li><a href="../index.html" target="_blank"><span class="icon"></span>官网首页</a></li>
    <li><a href="../资讯列表页.html" target="_blank"><span class="icon"></span>活动资讯</a></li>
    <li><a href="../游戏攻略列表.html" target="_blank"><span class="icon"></span>游戏攻略</a></li>
    <li><a href="javascript:;" target="_blank"><span class="icon"></span>游戏论坛</a></li>
    <li><a href="../图鉴列表.html" target="_blank"><span class="icon"></span>游戏图库</a></li>
    <li><a href="javascript:;" target="_blank"><span class="icon"></span>礼包兑换</a></li>
</ul>
<div class="fr wechat">
    <div class="wechat-ac">
        <span class="fl ficon ficon-wechat wechat-ac-icon"></span>
    </div>
    <div class="wechat-hover">
        <div class="media clear">
            <div class="fl">
                <img src="http://ossweb-img.qq.com/images/wushuang/pc20151208/qrcode.jpg"
                     alt="微信公众账号二维码" width="130" height="130" class="media-object">
            </div>
            <div class="media-body">
                <h4 class="pop-title">如何关注 全民无双 公众帐号</h4>
                <ol class="list">
                    <li>A 微信扫描二维码</li>
                    <li>B 微信搜索公众号 <span class="highline">全民无双</span></li>
                </ol>
            </div>
        </div>
    </div>
</div>